language: php

php:
  - 5.6
  - 7.0
  - 7.1
  - hhvm

install:
  - composer install

script: sh -c "if [ \"$TRAVIS_PHP_VERSION\" != 'hhvm' ]; then phpunit --coverage-clover=coverage.clover; else phpunit; fi"

after_script:
  - sh -c "if [ \"$TRAVIS_PHP_VERSION\" != 'hhvm' ]; then wget https://scrutinizer-ci.com/ocular.phar; fi"
  - sh -c "if [ \"$TRAVIS_PHP_VERSION\" != 'hhvm' ]; then php ocular.phar code-coverage:upload --format=php-clover coverage.clover; fi"
